### ISSUE TITLE
mailsnag in eclipse mars sr1 with warning

### ISSUE THREAD

**Issue by nimo23** [foosbar/mailsnag#5]
Eclipse Mars SR1 shows the following warning when mailsnag is installed:

The 'org.eclipse.ui.startup' extension from 'com.foosbar.mailsnag' does not provide a 'class' attribute.
This usage is deprecated and a 'class' attribute should be provided.
The release after Mars (4.5) will no longer support the deprecated usage!

Please fix that. Thanks!

**Comment by foosbar** [comment]
Sure, I'll take a look.

**Comment by foosbar** [comment]
I removed the startup extension since it wasn't used.
